## Task 2: Train Multiple Models
## Cell 1: Notebook title
## Day 07 — Model Comparison

This notebook trains and compares multiple machine learning models
(Logistic Regression, k-NN, and Naive Bayes) using the same binary
classification dataset (Spam vs Ham).

## Cell 2: Import required libraries

In [1]:
# Data handling
import pandas as pd
import numpy as np

# Text vectorization
from sklearn.feature_extraction.text import CountVectorizer

# Models
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB

# Evaluation metrics
from sklearn.metrics import accuracy_score, precision_score, recall_score

## Cell 3: Create the Dataset

In [2]:
# Create the dataset

emails = [
    "Win a free phone now!",
    "Meeting at 10 am",
    "Claim your prize today",
    "Lunch tomorrow?",
    "You won $1000",
    "Project deadline extended",
    "Congratulations! You won",
    "Can we reschedule?",
    "Limited time offer just for you",
    "Team meeting postponed"
]

labels = [
    "Spam",
    "Ham",
    "Spam",
    "Ham",
    "Spam",
    "Ham",
    "Spam",
    "Ham",
    "Spam",
    "Ham"
]

# Features (X) and target (y)
X = emails
y = labels

## Cell 4: Convert text to numerical features

In [3]:
# Convert text to numerical features
from sklearn.feature_extraction.text import CountVectorizer

# Initialize the vectorizer
vectorizer = CountVectorizer()

# Fit the vectorizer on the emails and transform
X_vectorized = vectorizer.fit_transform(X)

# Optional: check the feature names
print("Features:", vectorizer.get_feature_names_out())
print("Vectorized shape:", X_vectorized.shape)

Features: ['10' '1000' 'am' 'at' 'can' 'claim' 'congratulations' 'deadline'
 'extended' 'for' 'free' 'just' 'limited' 'lunch' 'meeting' 'now' 'offer'
 'phone' 'postponed' 'prize' 'project' 'reschedule' 'team' 'time' 'today'
 'tomorrow' 'we' 'win' 'won' 'you' 'your']
Vectorized shape: (10, 31)

## Cell 5: Prepare a container for storing results

In [4]:
# Create an empty list to store model results
results = []

# Each item will be a dictionary like:
# {"Model": "Logistic Regression", "Accuracy": 0.9, "Precision": 0.88, "Recall": 0.92}

# Optional: quick print to confirm it's empty
print("Results container initialized:", results)

Results container initialized: []

## Cell 6: Logistic Regression

In [5]:
# Import model and metrics (if not already imported)
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score

# Initialize Logistic Regression
lr_model = LogisticRegression()

# Train the model
lr_model.fit(X_vectorized, y)

# Make predictions
lr_preds = lr_model.predict(X_vectorized)

# Calculate metrics
lr_accuracy = accuracy_score(y, lr_preds)
lr_precision = precision_score(y, lr_preds, pos_label="Spam")
lr_recall = recall_score(y, lr_preds, pos_label="Spam")

# Store results
results.append({
    "Model": "Logistic Regression",
    "Accuracy": lr_accuracy,
    "Precision": lr_precision,
    "Recall": lr_recall
})

# Optional: print predictions and metrics
print("Logistic Regression predictions:", lr_preds)
print("Metrics:", lr_accuracy, lr_precision, lr_recall)

Logistic Regression predictions: ['Spam' 'Ham' 'Spam' 'Ham' 'Spam' 'Ham' 'Spam' 'Ham' 'Spam' 'Ham']
Metrics: 1.0 1.0 1.0

## Cell 7: k-NN (k = 3)

In [6]:
# Import k-NN model (if not already imported)
from sklearn.neighbors import KNeighborsClassifier

# Initialize k-NN with k = 3
knn_model = KNeighborsClassifier(n_neighbors=3)

# Train the model
knn_model.fit(X_vectorized, y)

# Make predictions
knn_preds = knn_model.predict(X_vectorized)

# Calculate metrics
knn_accuracy = accuracy_score(y, knn_preds)
knn_precision = precision_score(y, knn_preds, pos_label="Spam")
knn_recall = recall_score(y, knn_preds, pos_label="Spam")

# Store results
results.append({
    "Model": "k-NN (k=3)",
    "Accuracy": knn_accuracy,
    "Precision": knn_precision,
    "Recall": knn_recall
})

# Optional: print predictions and metrics
print("k-NN predictions:", knn_preds)
print("Metrics:", knn_accuracy, knn_precision, knn_recall)

k-NN predictions: ['Ham' 'Ham' 'Ham' 'Ham' 'Spam' 'Ham' 'Spam' 'Ham' 'Spam' 'Ham']
Metrics: 0.8 1.0 0.6

## Cell 8: Naive Bayes

In [7]:
# Import Naive Bayes model (if not already imported)
from sklearn.naive_bayes import MultinomialNB

# Initialize Naive Bayes
nb_model = MultinomialNB()

# Train the model
nb_model.fit(X_vectorized, y)

# Make predictions
nb_preds = nb_model.predict(X_vectorized)

# Calculate metrics
nb_accuracy = accuracy_score(y, nb_preds)
nb_precision = precision_score(y, nb_preds, pos_label="Spam")
nb_recall = recall_score(y, nb_preds, pos_label="Spam")

# Store results
results.append({
    "Model": "Naive Bayes",
    "Accuracy": nb_accuracy,
    "Precision": nb_precision,
    "Recall": nb_recall
})

# Optional: print predictions and metrics
print("Naive Bayes predictions:", nb_preds)
print("Metrics:", nb_accuracy, nb_precision, nb_recall)

Naive Bayes predictions: ['Spam' 'Ham' 'Spam' 'Ham' 'Spam' 'Ham' 'Spam' 'Ham' 'Spam' 'Ham']
Metrics: 1.0 1.0 1.0

## Task 3: Evaluation Metrics

In [8]:
# Convert results list to DataFrame
results_df = pd.DataFrame(results)

# Display the comparison table
print("Model Comparison Table:")
results_df

Model Comparison Table:

                 Model  Accuracy  Precision  Recall
0  Logistic Regression       1.0        1.0     1.0
1           k-NN (k=3)       0.8        1.0     0.6
2          Naive Bayes       1.0        1.0     1.0

## PART B — Bias–Variance Tradeoff
## Task 4: Underfitting vs Overfitting Experiment (Option A: k-NN)

In [9]:
from sklearn.model_selection import train_test_split

# Split dataset into train and test sets (30% test)
X_train, X_test, y_train, y_test = train_test_split(
    X_vectorized, y, test_size=0.3, random_state=42
)

In [13]:
from sklearn.neighbors import KNeighborsClassifier

# Convert sparse matrix to dense array (k-NN prefers dense)
X_dense = X_vectorized.toarray()

# Split dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X_dense, y, test_size=0.3, random_state=42
)

# k = 1 → overfitting
knn1 = KNeighborsClassifier(n_neighbors=1)
knn1.fit(X_train, y_train)

# Train and test accuracy
train_acc1 = knn1.score(X_train, y_train)
test_acc1 = knn1.score(X_test, y_test)

print("k=1 (High Variance) → Train Accuracy:", train_acc1)
print("k=1 (High Variance) → Test Accuracy:", test_acc1)

k=1 (High Variance) → Train Accuracy: 1.0
k=1 (High Variance) → Test Accuracy: 1.0

In [14]:
# k = 5 → high bias / underfitting
# Ensure k <= number of training samples
knn5 = KNeighborsClassifier(n_neighbors=5)
knn5.fit(X_train, y_train)

# Train and test accuracy
train_acc5 = knn5.score(X_train, y_train)
test_acc5 = knn5.score(X_test, y_test)

print("k=5 (High Bias) → Train Accuracy:", train_acc5)
print("k=5 (High Bias) → Test Accuracy:", test_acc5)

k=5 (High Bias) → Train Accuracy: 0.42857142857142855
k=5 (High Bias) → Test Accuracy: 0.6666666666666666

In [16]:
import pandas as pd

# Create a table showing train and test accuracy for both k-NN versions
bias_variance_results = pd.DataFrame({
    "Model": ["k-NN", "k-NN"],
    "k": [1, 5],  # matches the fixed k values
    "Train Accuracy": [train_acc1, train_acc5],
    "Test Accuracy": [test_acc1, test_acc5]
})

# Display the table
bias_variance_results

  Model  k  Train Accuracy  Test Accuracy
0  k-NN  1        1.000000       1.000000
1  k-NN  5        0.428571       0.666667